version: "3.7"
services:
  node-api:
    build:
      context: ./src
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Jeremiah-Ropo
      MONGO_INITDB_ROOT_PASSWORD: $Jeremiah59
